pharo-ide/Calypso

Calypso-Environment-Core.package/ClyEnvironmentContentMetadata.class/instance/newCursor.st
Calypso-Tools-CoreBrowser.package/ClyBrowser.class/instance/changeNavigationStateBy..st
Calypso-Tools-CoreBrowser.package/ClyDataSource.class/instance/environmentChanged..st
Calypso-Tools-CoreBrowser.package/ClyDataSourceSelection.class/instance/asItemsScope..st
Calypso-Tools-CoreBrowser.package/ClyDataSourceSelection.class/instance/asItemsScope.st
Calypso-Tools-CoreBrowser.package/ClyDataSourceSelection.class/instance/query..st
Calypso-Tools-CoreBrowser.package/ClyDataSourceSelection.class/instance/query.inScope..st

extra guard to skip update of closed data source
changeNavigationStateBY: is fixed to always update UI when navigation block is succeed. When there were errors updating will not happen

few fixes for release

---

Calypso-Environment-System.package/ClyMethodScope.class/instance/basisObjects..st

MethodScope should manage basis as IdentitySet because simple method equality  is very specific for compioled methods which is not suitable to cache scopes

MethodScope basis type is fixed

---

Calypso-NavigationModel.package/ClyAsyncQueryResult.class/instance/buildActualResult.st
Calypso-NavigationModel.package/ClyAsyncQueryResult.class/instance/collectMetadata.st
Calypso-NavigationModel.package/ClyNavigationEnvironment.class/instance/cleanGarbageInCache.st
Calypso-NavigationModel.package/ClyNavigationEnvironment.class/instance/initialize.st
Calypso-NavigationModel.package/ClyNavigationEnvironment.class/instance/query..st
Calypso-NavigationModel.package/ClyNavigationEnvironment.class/instance/updateUsing.by..st
Calypso-NavigationModel.package/ClyNavigationEnvironment.class/properties.json
Calypso-NavigationModel.package/WeakValueDictionary.extension/instance/clyCleanGarbage.st
Calypso-SystemPlugins-Reflectivity-Queries.package/MetalinkChanged.extension/instance/affectsMethod..st
Calypso-SystemPlugins-Reflectivity-Queries.package/MetalinkChanged.extension/instance/canAffectResultOfMethodQuery..st

- Query cache is correctly protected
- Query cache garbage collection is optimized
- MetalingChanged handing is fixed. Now method query results are corectly updated by it.
- improved async query building process:
special loop to prevent race condition when actual query is reset just after execution
and metadata collection without mutex protection which broke actual made background processing not really background and could lead to deadlock

More bug fixes

---

Calypso-SystemPlugins-Flags-Browser.package/ClyFlaggingMethods.extension/instance/decorateResultMethodEditor..st
Calypso-SystemPlugins-InheritanceAnalysis-Queries.package/ClyInheritanceAnalysisEnvironmentPlugin.class/instance/checkClassIsAbstract..st
Calypso-SystemPlugins-InheritanceAnalysis-Queries.package/ClyInheritanceAnalysisEnvironmentPlugin.class/instance/decorateBrowserItem.ofClass..st
Calypso-SystemPlugins-InheritanceAnalysis-Queries.package/ClyRequiredMethodGroupProvider.class/instance/isStatic.st
Calypso-SystemTools-Core.package/ClyMethodCreationTool.class/instance/applyChanges.st

method creation with better logic to create method with specified tag if exist instead of tagging it at second step.
requiredMethod group is fixed
flaggingMethods query decorating method editor to select flag message

missingParts

---

Calypso-SystemTools-FullBrowser.package/ClyFullBrowser.class/instance/specifyMethodItemNameOn.for..st

Now when inherited methdos  are visible in full browser the local methods are not highlighted as bold. 
Practice shows that it looks strange and not really helps

disableBoldingMethods

---

Calypso-Browser.package/ClyQueryView.class/instance/adoptForDialog.st

fix query view adoptation for the dialog mode.
In case when it is background query and not built yet it should be full mode view

fixForQueryViewDialogAdoptation

---

Calypso-Browser.package/ClyQueryView.class/instance/updateSelection.st
Calypso-Browser.package/ClyStatusBar.class/instance/defaultColor.st
Calypso-Browser.package/ClyStatusBar.class/properties.json
Calypso-Browser.package/ClyToolbar.class/properties.json
Calypso-Browser.package/Pharo3DarkTheme.extension/instance/calypsoFrozenItemColor.st
Calypso-Browser.package/Pharo3DarkTheme.extension/properties.json
Calypso-Browser.package/UITheme.extension/instance/calypsoFrozenItemColor.st
Calypso-SystemPlugins-Critic-Browser.package/ClyCriticDecorator.class/instance/adoptBrowserToolLayout.st
Calypso-SystemPlugins-Critic-Queries.package/ClyCriticEnvironmentPlugin.class/class/isEnabled..st
Calypso-SystemPlugins-Critic-Queries.package/ClyCriticEnvironmentPlugin.class/class/isEnabled.st
Calypso-SystemPlugins-Critic-Queries.package/ClyCriticEnvironmentPlugin.class/class/providesMethodGroupByDefault.st
Calypso-SystemPlugins-Critic-Queries.package/ClyCriticEnvironmentPlugin.class/class/settingsOn..st
Calypso-SystemPlugins-Monticello-Browser.package/ClyCommitMCPackageCommand.class/instance/execute.st
Calypso-SystemTools-Core.package/ClyMethodCreationTool.class/instance/applyChanges.st
Calypso-SystemTools-Core.package/SycCopyMethodNameToClypboardCommand.extension/class/methodContextMenuActivation.st
Calypso-SystemTools-Core.package/SycCopyMethodNameToClypboardCommand.extension/class/methodTabIconActivation.st
Calypso-SystemTools-Core.package/SycCopyMethodNameToClypboardCommand.extension/properties.json
Calypso-SystemTools-FullBrowser.package/ClyConvertMethodGroupToTagCommand.class/class/fullBrowserContextMenuActivation.st
Calypso-SystemTools-FullBrowser.package/ClyMoveMethodGroupsToPackageCommand.class/class/fullBrowserContextMenuActivation.st
Calypso-SystemTools-FullBrowser.package/ClyTextEditor.extension/instance/browseIt.st

- Copy method name to clipboard command. It is very usefull for any bug reports. It is added as tab icon and to extra context menu group 
- critiques method group is disabled by default. It can be enabled in settings browser
- #225 fixed
- tab selection fix
- commit command is adopted for latest iceberg. Kommitter logic is removed.
- fix dark theme problem in pharo 7 #247
- fix for browser updating after theme changes

Bug fixes and improvements

---

Calypso-Browser.package/ClyQueryView.class/instance/updateSelection.st
Calypso-Browser.package/ClyStatusBar.class/instance/defaultColor.st
Calypso-Browser.package/ClyStatusBar.class/properties.json
Calypso-Browser.package/ClyToolbar.class/properties.json
Calypso-Browser.package/Pharo3DarkTheme.extension/instance/calypsoFrozenItemColor.st
Calypso-Browser.package/Pharo3DarkTheme.extension/properties.json
Calypso-Browser.package/UITheme.extension/instance/calypsoFrozenItemColor.st
Calypso-SystemPlugins-Critic-Browser.package/ClyCriticDecorator.class/instance/adoptBrowserToolLayout.st
Calypso-SystemPlugins-Critic-Queries.package/ClyCriticEnvironmentPlugin.class/class/isEnabled..st
Calypso-SystemPlugins-Critic-Queries.package/ClyCriticEnvironmentPlugin.class/class/isEnabled.st
Calypso-SystemPlugins-Critic-Queries.package/ClyCriticEnvironmentPlugin.class/class/providesMethodGroupByDefault.st
Calypso-SystemPlugins-Critic-Queries.package/ClyCriticEnvironmentPlugin.class/class/settingsOn..st
Calypso-SystemPlugins-Monticello-Browser.package/ClyCommitMCPackageCommand.class/instance/execute.st
Calypso-SystemTools-Core.package/ClyMethodCreationTool.class/instance/applyChanges.st
Calypso-SystemTools-Core.package/SycCopyMethodNameToClypboardCommand.extension/class/methodContextMenuActivation.st
Calypso-SystemTools-Core.package/SycCopyMethodNameToClypboardCommand.extension/class/methodTabIconActivation.st
Calypso-SystemTools-Core.package/SycCopyMethodNameToClypboardCommand.extension/properties.json
Calypso-SystemTools-FullBrowser.package/ClyConvertMethodGroupToTagCommand.class/class/fullBrowserContextMenuActivation.st
Calypso-SystemTools-FullBrowser.package/ClyMoveMethodGroupsToPackageCommand.class/class/fullBrowserContextMenuActivation.st
Calypso-SystemTools-FullBrowser.package/ClyTextEditor.extension/instance/browseIt.st

- Copy method name to clipboard command. It is very usefull for any bug reports. It is added as tab icon and to extra context menu group 
- critiques method group is disabled by default. It can be enabled in settings browser
- #225 fixed
- tab selection fix
- commit command is adopted for latest iceberg. Kommitter logic is removed.
- fix dark theme problem in pharo 7 #247
- fix for browser updating after theme changes

Bugs fixes and improvements

---

src/Calypso-SystemQueries-Tests/ClyConstantMethodQueryTests.class.st
src/Calypso-SystemQueries/ClyConstantMethodQuery.class.st

Now constant method query takes into account the scope.
It fixes #331

scopedConstantQuery

---

src/Calypso-SystemPlugins-Spotter/ClyOpenSpotterMenuCommand.class.st

modify key combination for spotter and add toolbar item
Fixes #329

329-cmd-slash-does-not-works-on-windows

---

src/Calypso-SystemQueries/ClyClassQuery.class.st

Correct bug when a package extend a class in instance and class side.
The probem is that in the filteredClasses we will sometimes add two time the same class because there is the instance side result and the class side result. With this fix we use a Set to manage this case.
Fixes #372

372-Error-when-browsing-extensions-when-we-extend-instance-and-classe-side

---

src/BaselineOfCalypso/BaselineOfCalypso.class.st

I want to reduce future conflicts of baseline when we merge dev into master. Idea that dev branch should bring all fixes of dependencies and therefore dev branch uses floating versions. But master branch should use static versions which I will change directly in master branch after this PR. 
So new PRs will not conflict baseline and will not break those rules.
In addition it brings fix for #421.

To reduce future conflicts with baseline versions

---

src/Calypso-SystemPlugins-SUnit-Browser/ClyTestSetUpEditorTool.class.st

#425: fix bad override without super call

425-Error-when-creating-a-setUp-method-for-a-test

---

src/Calypso-SystemTools-Core/ClyBrowserMorph.extension.st

#424: #confirmUnusedClasses should check subclasses and trait users.
It adds same guards like in RBRemoveClassRefactoring which will allow to ignore own refactoring warnings and continue removal even when class has any kind of users

424-Cannot-remove-a-class-that-has-spurious-references-to-it

---

src/Calypso-SystemTools-QueryBrowser/ClyBrowserMorph.extension.st
src/Calypso-SystemTools-QueryBrowser/ClyBrowserToolMorph.extension.st
src/Calypso-SystemTools-QueryBrowser/ClyQueryBrowser.class.st

Fixes #437:  spawn query browser request is now checking if given query is empty before open the browser.
This change requires do not return instance of spawned browser because in case of empty query it is not returned anymore. So all returning sentences are removed. They were not used and to prepare spawned browser there is a block parameter in spawn method.

437-Possibility-to-not-open-a-MessageBrowser-if-there-is-no-sendersimplementors

---

src/Calypso-SystemPlugins-ClassScripts-Queries/ClyClassScript.class.st

#444: check that given class understands script selector instead of is kind logic
It also fixes examples methods defined in traits

444-Class-initialize-button-problem-when-installed-from-a-Trait-

---

src/Calypso-SystemTools-Core/SycMoveMethodsToClassCommand.extension.st

As agreed - here's the fix for the missing annotation. Fixes #448

448 move methods to class doesn't appear in menu but there is a command

---

src/Calypso-SystemPlugins-InheritanceAnalysis-Queries/ClyInheritanceAnalysisEnvironmentPlugin.class.st
src/Calypso-SystemPlugins-InheritanceAnalysis-Queries/ClyOverriddenSuperclassesChanged.class.st
src/Calypso-SystemPlugins-InheritanceAnalysis-Queries/ClyOverridingSubclassesChanged.class.st
src/Calypso-SystemTools-FullBrowser/ClyFullBrowser.class.st

- Overrides analysis should use instance side when processes class definition changes
- add missing task bar icon (improved #434 )

445 calypso doesnt always correctly show the diamond indicator for an overridden method

---

src/Calypso-SystemTools-FullBrowser/ClyVariableContextOfFullBrowser.class.st

When nothing is selected in variables pane the type of query items is analyzed to select appropriate context. And in that case it is ClyVariable subclasses.

Fixes #453: variable context should be used for items of variables query

---

src/Calypso-SystemQueries-Tests/ClyClassCommentsQueryTest.class.st

Test cases now always have tests and this test used test class to check how query works on classes without comment.
Now test creates anonymous subclass for this purpose.

Update 0.16.x: fix test for Pharo 8

---

src/Calypso-SystemQueries-Tests/ClyClassCommentsQueryTest.class.st

This test used a test class to check how query works on classes without comment.
But now in Pharo 8 all tests have a comment by default. 
So this PR modifies test to use anonymous subclass of Object as example of class without comment

Fix test for class comments query which fails in Pharo 8

---

src/Calypso-SystemTools-OldToolCompatibillity/ClyOldMessageBrowserAdapter.class.st
src/Calypso-SystemTools-QueryBrowser/ClyQueryBrowser.class.st

It fixes #476: #browseClasses: API for query browser
Example:
Smalltalk tools messageList browseClasses: {Array. Point}

476-Add-new-API-to-browse-classes-using-query-browser

---

src/Calypso-SystemQueries-Tests/ClyClassCommentsQueryTest.class.st

New message is added to support old Nautilus openOnEnvironment use cases.
```Smalltalk
Smalltalk tools messageList browseClasses: {Point. Array}
```

New version: API to browse classes using query browser

---

src/Calypso-SystemQueries-Tests/ClyClassCommentsQueryTest.class.st

New message is added to support old Nautilus openOnEnvironment use cases.
```Smalltalk
Smalltalk tools messageList browseClasses: {Point. Array}
```

0.16.x update: message to browse classes using query browser
