pharo-ide/Calypso

Calypso-Plugins-Critic-Environment.package/CompiledMethod.extension/instance/computeCritiquesBy..st
Calypso-Plugins-Critic-Environment.package/CompiledMethod.extension/properties.json

Fix for method critiques updating when method was removed

Fix for method critiques updating when method was removed

---

Calypso-Plugins-SUnit-Browser.package/ClyTestSetUpEditorTool.class/instance/editingMethod..st
Calypso-Tools-CoreBrowser.package/ClyMethodCodeEditorTool.class/instance/applyChanges.st
Calypso-Tools-CoreBrowser.package/ClyMethodCodeEditorTool.class/instance/belongsToRemovedBrowserContext.st
Calypso-Tools-CoreBrowser.package/ClyMethodCodeEditorTool.class/instance/editingMethod..st

SUnit browser plugin: test setUp editor is fixed to not modify context during accepting changes

test setUp editor is fixed

---

Calypso-Environment-System.package/ClyMethodGroup.class/instance/isAffectedByClassChange..st

fix logic when method group is affected by class change.
It fixes updating problem when methods of selected group are not updated during test ran

method group updating logic fix

---

Calypso-Tools-CoreBrowser.package/ClyBrowser.class/instance/isNavigationPanelFocused.st
Calypso-Tools-CoreBrowser.package/ClyBrowser.class/instance/switchFocusToNextPane.st
Calypso-Tools-CoreBrowser.package/ClyBrowser.class/instance/switchFocusToPreviousPane.st
Calypso-Tools-CoreBrowser.package/ClyNavigationView.class/instance/hasKeyboardFocus.st
Calypso-Tools-CoreBrowser.package/ClyNavigationView.class/instance/takeKeyboardFocus.st
Calypso-Tools-CoreBrowser.package/ClySwitchFocusToNextBrowserPaneCommand.class/instance/browser..st
Calypso-Tools-CoreBrowser.package/ClySwitchFocusToNextBrowserPaneCommand.class/instance/browser.st
Calypso-Tools-CoreBrowser.package/ClySwitchFocusToNextBrowserPaneCommand.class/instance/canBeExecutedInContext..st
Calypso-Tools-CoreBrowser.package/ClySwitchFocusToNextBrowserPaneCommand.class/instance/execute.st
Calypso-Tools-CoreBrowser.package/ClySwitchFocusToNextBrowserPaneCommand.class/instance/readParametersFromContext..st
Calypso-Tools-CoreBrowser.package/ClySwitchFocusToNextBrowserPaneCommand.class/properties.json
Calypso-Tools-CoreBrowser.package/ClySwitchFocusToPreviousBrowserPaneCommand.class/instance/browser..st
Calypso-Tools-CoreBrowser.package/ClySwitchFocusToPreviousBrowserPaneCommand.class/instance/browser.st
Calypso-Tools-CoreBrowser.package/ClySwitchFocusToPreviousBrowserPaneCommand.class/instance/canBeExecutedInContext..st
Calypso-Tools-CoreBrowser.package/ClySwitchFocusToPreviousBrowserPaneCommand.class/instance/execute.st
Calypso-Tools-CoreBrowser.package/ClySwitchFocusToPreviousBrowserPaneCommand.class/instance/readParametersFromContext..st
Calypso-Tools-CoreBrowser.package/ClySwitchFocusToPreviousBrowserPaneCommand.class/properties.json
Calypso-Tools-SystemBrowser.package/ClySwitchFocusToNextBrowserPaneCommand.extension/class/systemBrowserShortcutActivator.st
Calypso-Tools-SystemBrowser.package/ClySwitchFocusToNextBrowserPaneCommand.extension/properties.json
Calypso-Tools-SystemBrowser.package/ClySwitchFocusToPreviousBrowserPaneCommand.extension/class/systemBrowserShortcutActivator.st
Calypso-Tools-SystemBrowser.package/ClySwitchFocusToPreviousBrowserPaneCommand.extension/properties.json

Very simple support for focus navigation with arrow left/right.
It makes behaviour like in Nautilus

Focus based navigation is added

---

Calypso-SystemQueries.package/ClyDefaultSystemEnvironmentPlugin.class/instance/decorateBrowserItem.ofClass..st

fix comment check for metaclasses

fix comment check for metaclasses

---

Calypso-Browser.package/ClyBrowserState.class/instance/restoreNavigationStateOf..st
Calypso-Browser.package/ClyTabManager.class/instance/restoreBrowserState..st

Fix selected tab restore by navigation history

Fix selected tab restore by navigation history

---

Calypso-NavigationModel.package/ClyQuery.class/instance/fixStateBeforeExecution.st
Calypso-NavigationModel.package/ClyQuery.class/instance/requiredResult..st
Calypso-NavigationModel.package/ClyQuery.class/instance/shouldBeProtectedByWriteBarrier.st
Calypso-NavigationModel.package/ClyQuery.class/properties.json

Class var ShouldBeProtectedByWriteBarrier is added to disable protection logic when this VM feature is not available

optionalWriteBarrierQueryProtection

---

Calypso-NavigationModel.package/ClyNavigationEnvironment.class/instance/plugins.st
Calypso-NavigationModel.package/ClyQuery.class/class/disableWriteBarrierProtection.st
Calypso-NavigationModel.package/ClyQuery.class/class/enableWriteBarrierProtection.st
Calypso-SystemPlugins-Critic-Queries.package/ClyCriticEnvironmentPlugin.class/class/isSlow.st
Calypso-SystemPlugins-InheritanceAnalysis-Queries.package/ClyInheritanceAnalysisEnvironmentPlugin.class/class/isSlow.st
Calypso-SystemPlugins-InheritanceAnalysis-Queries.package/ClyInheritanceAnalysisEnvironmentPlugin.class/instance/resetCacheOfClass..st
Calypso-SystemPlugins-SUnit-Queries.package/ClyTestedEnvironmentPlugin.class/class/isSlow.st
Calypso-SystemQueries.package/ClySystemEnvironmentPlugin.class/class/disableSlowPlugins.st
Calypso-SystemQueries.package/ClySystemEnvironmentPlugin.class/class/enableSlowPlugins.st
Calypso-SystemQueries.package/ClySystemEnvironmentPlugin.class/class/isAutoActivated.st
Calypso-SystemQueries.package/ClySystemEnvironmentPlugin.class/class/isSlow.st
Calypso-SystemQueries.package/ClySystemEnvironmentPlugin.class/properties.json
Calypso-SystemTools-FullBrowser.package/ClyFullBrowser.class/instance/selectPackage.atClassTag..st

TelePharo fixes and optimizations
- slow logic for environment plugins
ClySystemEnvironmentPlugin disableSlowPlugins
fix method cache updating in inheritance plugin

telePharoAdoptation

---

Calypso-SystemPlugins-Monticello-Browser.package/ClyIcebergShowMethodVersionCommand.class/class/canBeExecutedInContext..st
Calypso-SystemPlugins-Monticello-Browser.package/ClyIcebergShowMethodVersionCommand.class/class/defaultMenuItemName.st
Calypso-SystemPlugins-Monticello-Browser.package/ClyIcebergShowMethodVersionCommand.class/class/methodBrowserMenuActivation.st
Calypso-SystemPlugins-Monticello-Browser.package/ClyIcebergShowMethodVersionCommand.class/class/methodBrowserTabActivation.st
Calypso-SystemPlugins-Monticello-Browser.package/ClyIcebergShowMethodVersionCommand.class/instance/browserTabActionIconName.st
Calypso-SystemPlugins-Monticello-Browser.package/ClyIcebergShowMethodVersionCommand.class/instance/execute.st
Calypso-SystemPlugins-Monticello-Browser.package/ClyIcebergShowMethodVersionCommand.class/instance/prepareFullExecutionInContext..st
Calypso-SystemPlugins-Monticello-Browser.package/ClyIcebergShowMethodVersionCommand.class/instance/setUpIconForMenuItem..st
Calypso-SystemPlugins-Monticello-Browser.package/ClyIcebergShowMethodVersionCommand.class/properties.json

add command to interfase with Iceberg

add-iceberg-showmethodversions

---

Calypso-SystemPlugins-Spotter.package/ClyClassCommentEditorTool.extension/instance/simpleNameForSpotterMenu.st
Calypso-SystemPlugins-Spotter.package/ClyClassDefinitionEditorTool.extension/instance/simpleNameForSpotterMenu.st
Calypso-SystemPlugins-Spotter.package/ClyMethodCodeEditorTool.extension/instance/simpleNameForSpotterMenu.st
Calypso-SystemTools-Core.package/ClyMethodEditorCommand.class/class/methodEditorMenuActivation.st
Calypso-SystemTools-Core.package/ClyRequestMethodPackageForEditorCommand.class/class/defaultMenuItemName.st
Calypso-SystemTools-Core.package/ClyRequestMethodPackageForEditorCommand.class/class/methodEditorShorcutActivation.st
Calypso-SystemTools-Core.package/ClyRequestMethodTagForEditorCommand.class/class/defaultMenuItemName.st
Calypso-SystemTools-Core.package/ClyRequestMethodTagForEditorCommand.class/class/methodEditorShorcutActivation.st

method editor commands improved to be in sportter menu

methodEditoCommandsInMenu

---

Calypso-NavigationModel.package/ClyUnknownQueryResult.class/instance/itemsStartingAt.count..st
Calypso-SystemTools-FullBrowser.package/ClyFullBrowser.class/instance/prepareDefaultState.st

fix default state of FullBrowser to focus package view

tinyFixForDefaultFocusInFulBrowser

---

Calypso-SystemPlugins-Monticello-Browser.package/ClyIcebergShowMethodVersionCommand.class/instance/execute.st

undeclared fix by temporal #asClass indirection (it is waiting 0.7 iceberg)

IcebergUndeclareFix

---

Calypso-SystemTools-FullBrowser.package/SycInspectVariableCommand.extension/class/fullBrowserDoubleClickActivation.st
Calypso-SystemTools-FullBrowser.package/SycInspectVariableCommand.extension/class/fullBrowserMenuActivation.st

fix missing activation for inspect variable command

missingActivationForVariableInspectCommand

---

Calypso-SystemTools-Core.package/ClyMethodEditorToolMorph.class/instance/tagEditingMethod..st

Fixe for #312:
Method editor should reject extension tags from logic to tag given method.

fix for #312

---

.smalltalk.ston
.travis.yml
scripts/preLoading.st
src/Calypso-Browser/ClyBrowserToolMorph.class.st
src/Calypso-SystemTools-Core/ClyMethodCodeEditorToolMorph.class.st
src/Calypso-SystemTools-Core/ClyMethodEditorCommand.class.st
src/Calypso-SystemTools-Core/ClyMethodEditorToolMorph.class.st
src/Calypso-SystemTools-Core/ClyMethodTagsAndPackageEditorMorph.class.st
src/Calypso-SystemTools-Core/ClyRequestMethodPackageForEditorCommand.class.st
src/Calypso-SystemTools-Core/ClyRequestMethodTagForEditorCommand.class.st
src/Calypso-SystemTools-Core/ClyResetMethodTagForEditorCommand.class.st

324 classify method does not works when coming from cmd

---

src/Calypso-SystemPlugins-SUnit-Browser/ClyRunAllTestsFromMethodDataSourceCommand.class.st
src/Calypso-SystemPlugins-SUnit-Browser/ClyRunFailedTestsFromMethodDataSourceCommand.class.st
src/Calypso-SystemPlugins-SUnit-Browser/ClyRunTestsFromMethodDataSourceCommand.class.st
src/Calypso-SystemPlugins-SUnit-Browser/ClyTestSetUpEditorTool.class.st
src/Calypso-SystemPlugins-SUnit-Queries/ClyCompositeTestResultProperty.class.st
src/Calypso-SystemPlugins-SUnit-Queries/ClySUnitEnvironmentPlugin.class.st
src/Calypso-SystemPlugins-SUnit-Queries/ClyTestResultProperty.class.st
src/Calypso-SystemPlugins-SUnit-Queries/ClyTestedEnvironmentPlugin.class.st

use methodClass instead of origin to collect test result

381-Error-when-browse-StringTest

---

src/BaselineOfCalypso/BaselineOfCalypso.class.st

To include the improvements in refactoring handling.

Updating SystemCommander & Commander

---

src/Calypso-Browser/ClyBrowserButtonMorph.class.st
src/Calypso-Browser/ClyBrowserCommand.class.st
src/Calypso-Browser/ClyBrowserContext.class.st
src/Calypso-Browser/ClyBrowserModeSwitchMorph.class.st
src/Calypso-Browser/ClyBrowserMorph.class.st
src/Calypso-Browser/ClyBrowserSearchDialogWindow.class.st
src/Calypso-Browser/ClyBrowserToolMorph.class.st
src/Calypso-Browser/ClyCloseBrowserCommand.class.st
src/Calypso-Browser/ClyContextSelectionStrategy.class.st
src/Calypso-Browser/ClyCursorPositionLabelMorph.class.st
src/Calypso-Browser/ClyQueryViewMorph.class.st
src/Calypso-Browser/ClyStatusBarItemMorph.class.st
src/Calypso-Browser/ClyStatusBarMorph.class.st
src/Calypso-Browser/ClyTextEditorToolMorph.class.st
src/Calypso-Browser/ClyTextLineNumbersSwitchMorph.class.st
src/Calypso-Browser/ClyTextMorphToolMorph.class.st
src/Calypso-Browser/ClyTextWrapModeSwitchMorph.class.st
src/Calypso-Browser/ClyToolContextNavigatorMorph.class.st
src/Calypso-Browser/ClyToolbarMorph.class.st

Prevent buggy condition during search dialog

---

src/Calypso-Browser/ClyBrowserButtonMorph.class.st
src/Calypso-Browser/ClyBrowserCommand.class.st
src/Calypso-Browser/ClyBrowserContext.class.st
src/Calypso-Browser/ClyBrowserModeSwitchMorph.class.st
src/Calypso-Browser/ClyBrowserMorph.class.st
src/Calypso-Browser/ClyBrowserSearchDialogWindow.class.st
src/Calypso-Browser/ClyBrowserToolMorph.class.st
src/Calypso-Browser/ClyCloseBrowserCommand.class.st
src/Calypso-Browser/ClyContextSelectionStrategy.class.st
src/Calypso-Browser/ClyCursorPositionLabelMorph.class.st
src/Calypso-Browser/ClyQueryViewMorph.class.st
src/Calypso-Browser/ClyStatusBarItemMorph.class.st
src/Calypso-Browser/ClyStatusBarMorph.class.st
src/Calypso-Browser/ClyTextEditorToolMorph.class.st
src/Calypso-Browser/ClyTextLineNumbersSwitchMorph.class.st
src/Calypso-Browser/ClyTextMorphToolMorph.class.st
src/Calypso-Browser/ClyTextWrapModeSwitchMorph.class.st
src/Calypso-Browser/ClyToolContextNavigatorMorph.class.st
src/Calypso-Browser/ClyToolbarMorph.class.st

Fix window label update when it is tabbed and collapsed

---

src/Calypso-SystemPlugins-SUnit-Browser/ClyTestSetUpEditorTool.class.st
src/Calypso-SystemTools-Core/ClyBrowserMorph.extension.st

Better class remove command

---

README.md

Add links to further documentation to help people learn more 
Also indicate that Calypso is now live in Pharo 7

Update README.md to provide links to more documenation

---

src/Calypso-SystemTools-Core/ClyBrowserMorph.extension.st

A small fix to practice contributing - still it improves things slightly

Correctly pluralise the senders message based on the count of senders

---

src/Calypso-SystemTools-Core/CDSharedVariableNode.extension.st

fix renamed CDSharedSlotNode extension

Fixes for classParser integration

---

src/Calypso-Browser/ClyBrowserMorph.class.st
src/Calypso-Browser/ClyTabManager.class.st

#165: Browser toogleFullWindowTabs. It is executed by double click on tab headers

165-Being-able-to-collapse-the-navigation-part

---

src/Calypso-Browser/ClyTabManager.class.st
src/Calypso-SystemTools-Debugger/ClyDebugger.class.st

Fix for broken tabs selection due to doubleClick handler of tab label

0.16 update: fix for broken tabs selection

---

src/Calypso-Browser/ClyTabManager.class.st
src/Calypso-SystemTools-Debugger/ClyDebugger.class.st

Fix for  broken tabs selection due to doubleClick handler of tab label

New release: fix for  broken tabs selection
